"""
Run CIGALE on PHANGS clusters and compare with SPECTRA results.

Usage:
    python scripts/run_cigale_phangs.py

Requirements:
    pip install cigale
"""

import os
import sys
import numpy as np
import pandas as pd
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

CIGALE_INPUT  = 'cigale_runs/phangs/cigale_input_phangs.txt'
CIGALE_OUTDIR = 'cigale_runs/phangs/output'
SPECTRA_SUMMARY = 'outputs/phangs_ic5332_no_dust/fit_summary.csv'


def create_cigale_config():
    """Create CIGALE pcigale.ini configuration for PHANGS clusters."""
    config = """
# CIGALE configuration for PHANGS HST star clusters
# Generated by SPECTRA comparison script

data_file = {input}
parameters_file =
sed_modules = sfhdelayed, bc03, nebular, dustatt_modified_starburst, redshifting
analysis_method = pdf_analysis
cores = 4

[sfhdelayed]
  tau_main = 100, 500, 1000
  age_main = 10, 50, 100, 500, 1000
  age_bursty =
  r_sfr =
  normalise = True

[bc03]
  imf = 1
  metallicity = 0.004, 0.008, 0.02
  separation_age = 10

[nebular]
  logU = -2.0
  zgas = 0.02
  ne = 100
  f_esc = 0.0
  f_dust = 0.0
  emission_lines_grouping = True

[dustatt_modified_starburst]
  E_BVs_young = 0.0, 0.1, 0.3, 0.5, 0.8
  E_BVs_old_factor = 0.44
  uv_bump_wavelength = 217.5
  uv_bump_width = 35.0
  uv_bump_amplitude = 0.0, 3.0
  powerlaw_slope = 0.0
  Ext_law_emission_lines = 1
  Rv = 3.1

[redshifting]
  redshift = 0.00184

[pdf_analysis]
  variables = stellar.mass, sfh.age, stellar.metallicity, attenuation.E_BVs_young
  save_best_sed = True
  save_chi2 = True
  lim_flag = True
  mock_flag = False
  block_size = 10000
  save_pdf = True
""".format(input=os.path.abspath(CIGALE_INPUT))

    os.makedirs(CIGALE_OUTDIR, exist_ok=True)
    config_path = os.path.join(CIGALE_OUTDIR, 'pcigale.ini')
    with open(config_path, 'w') as f:
        f.write(config)
    print(f"CIGALE config written: {config_path}")
    return config_path


def run_cigale():
    """Run CIGALE if available."""
    try:
        import pcigale
        os.chdir(CIGALE_OUTDIR)
        os.system('pcigale run')
        os.chdir(str(Path(__file__).parent.parent))
        print("CIGALE run complete.")
        return True
    except ImportError:
        print("pcigale not installed. Install with: pip install cigale")
        print("Skipping CIGALE run — will use mock comparison data.")
        return False


def load_cigale_results():
    """Load CIGALE output results table."""
    results_file = os.path.join(CIGALE_OUTDIR, 'results.fits')
    alt_file = os.path.join(CIGALE_OUTDIR, 'results.txt')

    if os.path.exists(results_file):
        from astropy.table import Table
        t = Table.read(results_file)
        return t.to_pandas()
    elif os.path.exists(alt_file):
        return pd.read_csv(alt_file, sep='\s+', comment='#')
    else:
        print(f"No CIGALE results found at {results_file}")
        return None


if __name__ == '__main__':
    # Step 1: Prepare input
    if not os.path.exists(CIGALE_INPUT):
        print("Preparing CIGALE input...")
        os.system('python scripts/prepare_cigale_input.py --source phangs --max-rows 5')

    # Step 2: Create config
    create_cigale_config()

    # Step 3: Run CIGALE
    ran = run_cigale()

    print(f"\nNext steps:")
    print(f"  cd {CIGALE_OUTDIR}")
    print(f"  pcigale run")
    print(f"  # Then run the comparison plot:")
    print(f"  python scripts/plot_spectra_vs_cigale.py")
